bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               LICENSE.txt,\
               CHANGELOG.md,\
               lib/core-3.8.3.jar,\
               lib/toml-3.8.3.jar
src.includes = LICENSE.txt
source.. = src/
bin.excludes = maven.properties
